"""Generate the gallery, component catalog, API summaries, and PNG previews."""
import argparse
import ast
from dataclasses import dataclass, fields
from importlib import import_module
import inspect
from pathlib import Path
import runpy
import sys
from tempfile import TemporaryDirectory
from textwrap import dedent

import beampath
from beampath import Path as BeamPath, Setup, Style
from beampath import components
from beampath.examples._discovery import example_names


PROJECT = Path(__file__).resolve().parents[1]
GENERATED = "<!-- Generated by scripts/rebuild_docs.py; edit the Python sources. -->\n\n"
NAV = "[README](../README.md) · [Gallery](gallery.md) · [Components](components.md) · [API](api.md)\n\n"


@dataclass
class Diagram:
    slug: str
    description: str
    code: str
    source: Path
    setup: BeamPath | Setup
    style: Style | None = None
    signature: str = ""


def example_source(source, filename="example.py"):
    """Use the complete file, removing only its leading module docstring."""
    tree = ast.parse(source, filename=str(filename))
    description = ast.get_docstring(tree)
    if not description or not description.strip():
        raise ValueError(f"{filename}: add a descriptive module docstring")
    code = "".join(source.splitlines(keepends=True)[tree.body[0].end_lineno:]).strip()
    if not code:
        raise ValueError(f"{filename}: missing example code")
    return description, code


def demo_source(demo):
    """Display the demo body verbatim, without its docstring and return setup."""
    source = dedent(inspect.getsource(demo))
    node = ast.parse(source).body[0]
    if node.args.args or node.args.kwonlyargs or node.args.vararg or node.args.kwarg:
        raise ValueError(f"{demo.__module__}: demo() must take no arguments")
    body = node.body[1:] if ast.get_docstring(node) else node.body
    last = body[-1]
    if not (isinstance(last, ast.Return) and isinstance(last.value, ast.Name)
            and last.value.id == "setup" and len(body) > 1):
        raise ValueError(f"{demo.__module__}: demo() must end with return setup")
    return dedent("".join(source.splitlines(keepends=True)[body[0].lineno - 1:last.lineno - 1])).strip()


def signature(obj, name=None):
    """Keep the real parameters and defaults, omitting types for a short summary."""
    sig = inspect.signature(obj)
    parameters = [p.replace(annotation=inspect.Parameter.empty)
                  for p in sig.parameters.values() if p.name != "self"]
    return (name or obj.__name__) + str(sig.replace(
        parameters=parameters, return_annotation=inspect.Signature.empty))


def validate_setup(setup, style, source):
    if not isinstance(setup, (BeamPath, Setup)):
        raise ValueError(f"{source}: define setup as a beampath Path or Setup")
    if style is not None and not isinstance(style, Style):
        raise ValueError(f"{source}: style must be a beampath Style")


def examples(project=PROJECT):
    diagrams = []
    for name in example_names(project / "examples"):
        source = project / "examples" / f"{name}.py"
        description, code = example_source(source.read_text(encoding="utf-8"), source)
        namespace = runpy.run_path(str(source))
        setup, style = namespace.get("setup"), namespace.get("style")
        validate_setup(setup, style, source)
        diagrams.append(Diagram(name, description, code, source, setup, style))
    return diagrams


def component_demos():
    diagrams = []
    for name in sorted(components.__all__, key=str.casefold):
        factory = getattr(components, name)
        module = import_module(factory.__module__)
        description = inspect.getdoc(factory)
        if not description:
            raise ValueError(f"{name}: add a factory docstring")
        demo = getattr(module, "demo", None)
        if not callable(demo):
            raise ValueError(f"{name}: add demo() to the component module")
        code = demo_source(demo)
        setup = demo()
        validate_setup(setup, None, module.__file__)
        diagrams.append(Diagram(name, description, code, Path(module.__file__), setup,
                                signature=signature(factory)))
    return diagrams


def fence(code):
    return f"```python\n{code}\n```\n\n"


def gallery_page(diagrams, project):
    page = GENERATED + "# Examples\n\n" + NAV
    page += ("Each file constructs a `setup`; the runner handles rendering. Copy a code block\n"
             "and call `setup.save(\"diagram.svg\")`, or run an example by its filename stem:\n\n"
             "```sh\npython -m beampath.examples --diagram hello --png\n```\n\n"
             "Outputs go to `build/examples/`. Use `--diagram all` for every example;\n"
             "add `--pdf` for PDF. PNG/PDF need the [export dependencies](api.md#export).\n"
             "When an example defines `style`, pass it to `setup.save(..., style=style)`.\n\n")
    page += " · ".join(f"[{d.slug}](#{d.slug})" for d in diagrams) + "\n\n"
    for diagram in diagrams:
        page += (f"## {diagram.slug}\n\n{diagram.description}\n\n"
                 f"![{diagram.slug} diagram](../examples/images/{diagram.slug}.png)\n\n"
                 + fence(diagram.code)
                 + f"[Source](../{diagram.source.relative_to(project).as_posix()})\n\n")
    return page.rstrip() + "\n"


def components_page(diagrams):
    page = GENERATED + "# Components\n\n" + NAV
    page += ("Import factories from `beampath.components` (also available from `beampath`).\n"
             "The optional first argument is the label: `None` uses the default, `\"\"` hides\n"
             "it, and `\\n` creates multiple lines. Each demo shows the component's open\n"
             "beam or fiber ports.\n\n")
    page += " · ".join(f"[{d.slug}](#{d.slug.lower()})" for d in diagrams) + "\n\n"
    for diagram in diagrams:
        source = f"../src/beampath/components/{diagram.source.name}"
        page += (f"## {diagram.slug}\n\n" + fence(diagram.signature)
                 + diagram.description + "\n\n"
                 + f'<img src="images/components/{diagram.slug}.png" alt="{diagram.slug} demo" width="420">\n\n'
                 + fence(diagram.code) + f"[Source]({source})\n\n")
    return page.rstrip() + "\n"


def api_summary():
    groups = {
        "Construction and connections": (
            beampath.beam, beampath.chain, beampath.rows, Setup, Setup.beam, Setup.add,
            BeamPath.append, BeamPath.out, BeamPath.end, BeamPath.connect, BeamPath.join,
            beampath.OpticRef.input, beampath.OpticRef.out,
        ),
        "Layout and export": (Setup.layout, Setup.to_svg, Setup.save),
        "Custom components": (
            beampath.ComponentSpec, beampath.ComponentDefinition, beampath.Artwork,
            beampath.Geometry, beampath.Port, beampath.component, beampath.register_component,
        ),
    }
    result = ""
    for title, objects in groups.items():
        result += f"### {title}\n\n| API | Purpose |\n|---|---|\n"
        for obj in objects:
            prop = isinstance(obj, property)
            obj = obj.fget if prop else obj
            doc = inspect.getdoc(obj)
            if not doc:
                raise ValueError(f"{obj.__qualname__}: missing API docstring")
            summary = " ".join(doc.split("\n\n", 1)[0].splitlines())
            # Dataclass constructor details belong beside the custom-component
            # example and in source, rather than overwhelming this short index.
            label = obj.__qualname__ if prop or (inspect.isclass(obj) and obj is not Setup) else signature(obj, obj.__qualname__)
            summary = summary.replace("|", r"\|")
            result += f"| `{label}` | {summary} |\n"
        result += "\n"
    result += "### Style\n\n" + inspect.getdoc(Style) + "\n\n"
    result += "| Field | Default |\n|---|---|\n"
    for field in fields(Style):
        result += f"| `{field.name}` | `{field.default!r}` |\n"
    return result.rstrip()


def replace_block(document, name, content, filename):
    begin, end = f"<!-- {name}:BEGIN -->", f"<!-- {name}:END -->"
    if document.count(begin) != 1 or document.count(end) != 1:
        raise ValueError(f"{filename}: expected one {name} block")
    before, rest = document.split(begin)
    _, after = rest.split(end)
    return before + begin + "\n" + content.rstrip() + "\n" + end + after


def render_preview(diagram, destination, *, width):
    try:
        diagram.setup.save(destination, style=diagram.style, width=width, dpi=600)
    except Exception as exc:
        raise RuntimeError(
            f"{diagram.source}: preview failed: {exc}\n"
            "PNG export needs beampath[png] and native Cairo; see docs/api.md#export."
        ) from exc


def rebuild_docs(project=PROJECT, *, check=False):
    project = project.resolve()
    example_diagrams = examples(project)
    demos = component_demos()
    hello = next(d for d in example_diagrams if d.slug == "hello")
    hello_block = (f"![{hello.description}](examples/images/hello.png)\n\n" + fence(hello.code))
    documents = {
        project / "docs/gallery.md": gallery_page(example_diagrams, project),
        project / "docs/components.md": components_page(demos),
    }
    for filename, marker, block in (("README.md", "HELLO", hello_block),
                                     ("docs/api.md", "API", api_summary())):
        path = project / filename
        documents[path] = replace_block(path.read_text(encoding="utf-8"), marker, block, path)
    outputs = {path: content.encode("utf-8") for path, content in documents.items()}
    build = project / "build"
    build.mkdir(exist_ok=True)
    with TemporaryDirectory(prefix="docs-", dir=build) as staging:
        for category, diagrams, width in (("examples/images", example_diagrams, 2400),
                                           ("docs/images/components", demos, 960)):
            for diagram in diagrams:
                temporary = Path(staging) / f"{len(outputs)}.png"
                render_preview(diagram, temporary, width=width)
                outputs[project / category / f"{diagram.slug}.png"] = temporary.read_bytes()
    # Only these directories contain generated previews; social artwork is separate.
    old_images = set((project / "examples/images").glob("*.png"))
    old_images.discard(project / "examples/images/hello-social.png")
    old_images.update((project / "docs/images/components").glob("*.png"))
    obsolete = old_images - outputs.keys()
    changed = [path for path, data in outputs.items() if not path.exists() or path.read_bytes() != data]
    stale = sorted(set(changed) | obsolete)
    if not check:
        for path in changed:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(outputs[path])
        for path in obsolete:
            path.unlink()
    return [path.relative_to(project).as_posix() for path in stale]


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Report stale outputs without replacing them")
    args = parser.parse_args()
    try:
        changed = rebuild_docs(check=args.check)
    except Exception as exc:
        print(f"Could not rebuild documentation: {exc}", file=sys.stderr)
        return 1
    if args.check and changed:
        print("Stale documentation:\n" + "\n".join(changed))
        return 1
    print("Documentation is current." if args.check else f"Rebuilt documentation; {len(changed)} files changed.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
